# Generated by Django 4.2.7 on 2023-12-10 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_starts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='starts',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
